### ISSUE TITLE
Non-Rails usage. 

### ISSUE THREAD

**Issue by konung** [lulalala/adequate_errors#7]
Hi. 

Since this gem intercepts Rails errors, does it mean that it is is Rails only? Or can it be used in other settings, like my own gems or Roda/Sinatra/Hanami?

**Comment by lulalala** [comment]
@konung strictly speaking, this gem is only related to model, not the overall web framework. If your model in Sinatra `include ActiveModel::Validations` then it should work.

What model class do you use? If it does not take too much time to port I may just do that.

**Comment by konung** [comment]
I meant would it work if there was Nothing to override . Like with a PORO model? With dry-validations ? No validation gem ?

Have a good day !

Nick

**Comment by lulalala** [comment]
Currently no, but I've asked dry-validations how they liked the idea of Error object.

For PORO model, there is no validations logic so I can't imagine what you want. Could you give some pseudo code as use case?

**Comment by konung** [comment]
Well a PORO object could still need error handling  if something happens during execution of the said PORO object it could fail and provide an accessible ErrorObject .


Here is a bit of a a contrived example

```ruby

class TranformCsvFile
  include AdequateErrors
  ....

  def run(path)
    csv = read_file(path)
    new_csv = transform_csv(csv)
    save_file(new_csv)
  end

  def read_file(path)
    # various errors here
  end


  def transform_csv(csv)
    # various errors here
  end

  def save_file(csv)
    # various errors here
  end
end

####

result = TanformCsvFile.new.run('path_to_file')
result.errors  # <-   something like this?

```



Have a great day!

Nick Gorbikoff
nick.gorbikoff@gmail.com

**Comment by lulalala** [comment]
Ok, so the idea is to have the object catching errors, and have these errors stored in the Errors object.

It sounds useful because we no longer have to worry about error handling from the outside.

Currently AdequateErrors only handle what ActiveModel::Errors handles, that is the model validation errors. The general "Ruby Error" is not really handled here.

I do feel this use case is suitable for a different layer though, which is service objects. For example, in https://github.com/AaronLasseigne/active_interaction we can easily have these exceptions collected when we `run` it. It can then assign the Ruby Errors into its Errors object. That's one way to catch all errors during the `run` execution without user writing any `rescue`.

**Comment by lulalala** [comment]
And after checking with developer of dry-validation, it has its own Error objects, which is accessible via `Result#message_set` method. It has a different philosophy to AdequateErrors, but still is better than just a bunch of strings.

Have a great day!

**Comment by konung** [comment]
@lulalala Thank you for looking into it.
